# Generated by Django 4.2.30 on 2026-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_board_excerpt_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
