# Generated by Django 4.2.30 on 2026-06-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
