# Generated by Django 4.2.30 on 2026-06-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
